config/routes.rb
Rails.application.routes.draw do

  get 'signup' => 'users#new'

  root 'static_pages#home' # root itself is a named route. root_path, and root_url will be created and ready for use.

  get 'help' => 'static_pages#help'
  
  get 'about' => 'static_pages#about'
  
  get 'contact' => 'static_pages#contact'
  
  resources :users do
    member do
      get :following, :followers
    end 
  end
  
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]

  
  
  
  
  
  
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @micropost  = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help
  end
  
  def about
  end
  
  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>



<h1>About</h1>

  <p aligh="left">
      This is a demo application created by <a href="http://daweilihomepage.weebly.com/">Dawei Li</a> by following
      the <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
      (by <a href="http://www.michaelhartl.com/">Michael Hartl</a>). 
      This application is developed in the <a href="https://c9.io/">Cloud9 IDE</a> and 
      is deployed on the <a href="https://www.heroku.com/">Heroku Platform</a>.
      The source code can be found at my BitBucket repository: <a href="https://bitbucket.org/douglasleer/sample_app">https://bitbucket.org/douglasleer/sample_app</a> 
      and also my GitHub repository: <a href="https://github.com/douglasleer/mini_post">https://github.com/douglasleer/mini_post</a>.
  </p>

  <p>
    Features supported:
    <ul>
      <li>General checking: Name field blank check. Email address format check. Password constraint check. Password confirmation.</li>
      <li>User profile updating: We allow user to change password and/or gravatar after log in. 
          Changing gravatar is out-sourced to <a href="https://en.gravatar.com/">https://en.gravatar.com/</a>. 
          You need an account at <a href="https://en.gravatar.com/">https://en.gravatar.com/</a> to use this feature.</li>
      <li>Administration account supported. The administrator user can delete any user, along with all the posts of a user.</li>
      <li>"Remember me" option. We use cookies to allow user logging in without password.</li>
      <li>Allow user to post 140-character minipost. (I can easily change it to more characters. 
      I just don't know why Twitter stick to 140 characters.)</li>
      <li>Allow user to upload an image along with a post. We check the file extension and size of the image. The size of an image is limited to 5MB. 
          We also resize the image for display if the image is greater than 400p * 400p.</li>
      <li>I am using AWS S3 for storing the users' images. Previously, I just stored the images as local files. 
      However, it seems that Heroku periodically deletes the images. So, I changed to AWS S3 cloud storage. </li>
      <li>Allow user to follow and unfollow other users. We use Ajax to let the use see whether the following/unfollowing operation
      is successful or not immediately without refreshing.</li>
      <li>Populating the user's home page with his/her own posts and the posts of users that he/she follows. All these posts are sorted according to their posted time.</li>
      <li>Allow pagination for a list of many items.</li>
      <li>Notice that, after logging in, the user's profile page consists of all posts of the user. The user's home page is where he/she can post a story. </li>
    </ul>
    Differences from the sample application in the book:
    <ul>
      <li>Chapter 10 (Account activation and password reset) in the book was skipped on purpose. After I finished reading the book, 
      I realized that this chapter can be skipped without affecting the integrity of the sample application. 
      So, I just skipped it, and it really does not affect the integrity of the whole application. I may consider adding this feature in the future.</li>
      <li>After logging in, the user will be redirected to his/her home page, instead of his/her profile page (which is what the author of the book did). 
      This makes more sense, because a user should be more interested in the posts of the users that he/she is following than his/her own profile.</li>
      <li>Various customized and additional information has been added to serve as my demo application.</li>
    </ul>
    Issues encountered and solutions:
    <ul>
      <li>In Chapter 2, when generating the users microposts with scaffolding. I delete the user1 through webpage. 
      And later access to user1 gave error. It took me some time to figure out the reason is that I deleted the first user;
      and after that, the first user will no longer have user id 1.</li>
      <li>Previously, I did not use AWS S3 cloud storage for user image uploads. It worked fine immediately after I upload some images.
      But after some time, typically, one hour, the uploaded images of will be deleted! It did not take me too long to find out that the
      reason is that Heroku is periodically deleting these images. Thus, I need to use cloud storage for image uploads.</li>
      <li>When configuring AWS S3 for image storage, I omitted setting the region for the created bucket (which is how the book did), and I encountered
      error; after checking the error log, I found the reason, and set the correct region for the created bucket.</li>
      <li>But this does not solve all the problems. I encountered 403 forbidden error. It turned out that granting access only in the S3 bucket cnosole is 
      not enough. We need to go to AWS console, Identity & Access Management (IAM), and 
      attach "AdministratorAccess" and "PowerAccessUser" policies to the user.</li>
    </ul>

  </p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
I can be reached at <a href="mailto:douglasleer@gmail.com">douglasleer@gmail.com</a>. 
Here is my homepage: <a href="http://daweilihomepage.weebly.com/">http://daweilihomepage.weebly.com/</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>



<h1>Help</h1>

<%= render 'shared/help_info' %>

<p>
  Check the amazing <a href="http://www.railstutorial.org/book">book</a> about how this application is built. 
  It is free! Besides, all the tools and platforms, such as <a href="https://bitbucket.org/">BitBucket</a>,
  <a href="https://c9.io/">Cloud9 IDE</a> and <a href="https://www.heroku.com/">Heroku Platform</a> are also free!
  You just need to register some free accounts.
</p>

<p>
  For more information on Ruby on Rails, go to <a href="http://rubyonrails.org/">http://rubyonrails.org/</a>.
</p>

app/views/static_pages/home.html.erb
<% if logged_in? %>
<div class="row">
    <aside class="col-md-4">
      <section class="user_info">
      <%= render 'shared/user_info' %> 
      </section>
      
      <section class="stats">
      <%= render 'shared/stats' %> 
      </section>
      
      <section class="micropost_form">
      <%= render 'shared/micropost_form' %> 
      </section>
    </aside>
    <div class="col-md-8">
      <h3>Micropost Feed</h3>
      <%= render 'shared/feed' %> 
    </div>

</div>


<% else %>
  <div class="center jumbotron">
  
  <h1>Welcome to MiniPost</h1>
  <p align="left">
      This is a demo application created by <a href="http://daweilihomepage.weebly.com/">Dawei Li</a> by following
      the <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
      (by <a href="http://www.michaelhartl.com/">Michael Hartl</a>). This application is similar to Twitter; it allows
      users to post their stories using less than or equal to 140 characters, and follow/unfollow other users.
  </p>
  
  <p align="left">There isn't too much you can see if you don't log in. So you can either <%= link_to "Sign Up", signup_path %> or <%= link_to "Log In", login_path %>.</p>
  
  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %> 
  <%= link_to "Log in now!", login_path, class: "btn btn-lg btn-primary" %>
  
  </div>
  
  <%= render 'shared/help_info' %>

Powered by: <br>
<%= link_to image_tag("rails.png", alt: "Rails logo"), 'http://rubyonrails.org/' %>
<% end %>